// web/src/components/ThemeToggle.vue
<script setup lang="ts">
import Button from "primevue/button";
import { useTheme } from "../composables/useTheme";
import AppIcon from "./AppIcon.vue";

withDefaults(
  defineProps<{
    size?: "small" | "large";
    iconSize?: number;
  }>(),
  { size: undefined, iconSize: 18 },
);

const { isDark, toggle } = useTheme();
</script>

<template>
  <Button
    text
    rounded
    severity="secondary"
    :size="size"
    :title="isDark ? 'Switch to light theme' : 'Switch to dark theme'"
    :aria-label="isDark ? 'Switch to light theme' : 'Switch to dark theme'"
    @click="toggle"
  >
    <Transition
      mode="out-in"
      enter-active-class="transition duration-200 ease-out"
      enter-from-class="-rotate-90 scale-0 opacity-0"
      enter-to-class="rotate-0 scale-100 opacity-100"
      leave-active-class="transition duration-150 ease-in"
      leave-from-class="rotate-0 scale-100 opacity-100"
      leave-to-class="rotate-90 scale-0 opacity-0"
    >
      <AppIcon
        :key="isDark ? 'sun' : 'moon'"
        :icon="{ type: 'lucide', value: isDark ? 'sun' : 'moon' }"
        :size="iconSize"
      />
    </Transition>
  </Button>
</template>

// web/src/components/theme/ThemeToggle.tsx
import { Moon, Sun } from 'lucide-react'
import { useTheme } from './useTheme'

export function ThemeToggle() {
  const { theme, setTheme } = useTheme()
  const isDark = theme === 'dark'

  const handleToggle = () => {
    setTheme(isDark ? 'light' : 'dark')
  }

  const label = isDark ? 'Switch to light theme' : 'Switch to dark theme'

  return (
    <button
      onClick={handleToggle}
      className="relative flex h-9 w-9 items-center justify-center rounded-lg border border-border bg-background transition hover:bg-muted"
      aria-label={label}
      type="button"
    >
      <Sun
        className="h-4 w-4 rotate-0 scale-100 transition-transform duration-200 dark:-rotate-90 dark:scale-0"
        aria-hidden="true"
      />
      <Moon
        className="absolute h-4 w-4 rotate-90 scale-0 transition-transform duration-200 dark:rotate-0 dark:scale-100"
        aria-hidden="true"
      />
    </button>
  )
}
